### ISSUE TITLE
not master and slaveOk=false

### ISSUE THREAD

**Issue by herlon214** [autopilotpattern/mongodb#17]
Hi guys, I was testing this project and when I access a container and try to execute a query but throws an Error:
```
Error: error: {
	"ok" : 0,
	"errmsg" : "not master and slaveOk=false",
	"code" : 13435,
	"codeName" : "NotMasterNoSlaveOk"
}
```

I think that the slaves needs to execute `rs.slaveOk()` to replicate the data.
I don't know if I am doing this right, could you help me?

Thanks in advance,

**Comment by yosifkit** [comment]
That sounds like it is correctly replicating the data and you happened to connect to one of the non-master nodes.

[ReadPreference](https://docs.mongodb.com/manual/core/read-preference/) is set on the connection, not the node, so it would need to go in your driver settings or done by you when connecting via a mongo shell with `rs.slaveOk()`.
